#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process without using kill or killall

pid=$(pgrep -f 4-to_infinity_and_beyond)
if [ -n "$pid" ]; then
  perl -e "kill 15, $pid"
fi
