#!/usr/bin/env bash
# This script prints different messages based on loop iteration using while and if-elif-else

count=1

while [ $count -le 10 ]
do
  if [ $count -eq 4 ]; then
    echo "bad luck"
  elif [ $count -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((count++))
done
